Fix volume control to actually compile on windows
D:\go\src\github.com\SvenWiltink\volumecontrol>go build
github.com\SvenWiltink\volumecontrol
# github.com/SvenWiltink/volumecontrol
.\volumecontrol_windows.go:75: undefined: i
.\volumecontrol_windows.go:78: missing return at end of function
.\volumecontrol_windows.go:81: undefined: i
.\volumecontrol_windows.go:84: missing return at end of function